### PR TITLE
Update filtering for max fraction infectivity and for curves where midpoint is substantially different from nt50

### PR DESCRIPTION
**Pull request by anloes**
The changes made here starts to address the issues described in #16 and #17 to improve QC of serum samples. Primarily, two changes were made:

1. I added a QC filter which compares the midpoint and the NT50 - I have added an additional filter added at the qc of the serum titers which flags any samples where there is significant variation on the calculated value for the midpoint of the curve and the nt50. This type of error mostly originates when the top of the curve is substantially less than or greater than 1. For samples where this is the case, we also determine information on whether the top of the curve is outside of bounds specified in the config. This information is not currently used in filtering but could be potentially be used to identify samples where the midpoint would be better than the nt50. At this point, I am using this filter primarily as a mechanism to flag samples that fail these parameters and then manually specifying the failed barcodes in the config. yaml. 

2. I moved the max fraction infectivity filtering to curve fitting step - As I think in many cases it may be preferable to remove barcodes from specific wells rather than from the entire plate when we identify a max_fraction_infectivity failure, I have removed this and the barcode_fraction_consistency flags from the process_counts step and added an automatic filter of any points that exceed the max fraction infectivity value to the curve fitting notebook. This occurs immediately prior to the clipping of the curves to the fraction infectivity ceiling so that they are excluded from the curve fitting calculation.

### CODE REVIEW

**Comment by anloes** [comment]
@jbloom It looks like the test is failing because it can't find /usr/share/miniconda/envs/seqneut-pipeline/bin/python3.11: No module named ruff. Is this an environment issue or a code issue?

**Comment by jbloom** [comment]
That's strange. It ran before, and as far as I can tell your pull request does not change either the `environment.yml` or `test.yml` file, correct?

**Comment by anloes** [comment]
It should not change the environment, but I did update the config.yml in the test_example directory so that it includes the added filters.

**Comment by jbloom** [comment]
This functionality should basically be implemented in version 2.0.0, so closing this pull request.

**Pull request closed without merging**
